### ISSUE TITLE
Error when logging from HostedService triggered by Timer

### ISSUE THREAD

**Issue by webseb** [roryprimrose/Divergic.Logging.Xunit#16]
When the Timer triggers the HostedService I get the following exception

````csharp
The active test run was aborted. Reason: Unhandled Exception: System.AggregateException: An error occurred while writing to logger(s). (There is no currently active test.) ---> System.InvalidOperationException: There is no currently active test.
   at Xunit.Sdk.TestOutputHelper.GuardInitialized() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 51
   at Xunit.Sdk.TestOutputHelper.QueueTestOutput(String output) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 62
   at Divergic.Logging.Xunit.TestOutputLogger.WriteLogEntry[TState](LogLevel logLevel, EventId eventId, TState state, String message, Exception exception, Func`3 formatter) in D:\a\1\s\Divergic.Logging.Xunit\TestOutputLogger.cs:line 69
   at Divergic.Logging.Xunit.FilterLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in D:\a\1\s\Divergic.Logging.Xunit\FilterLogger.cs:line 46
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
````
I saw that there was a fix in the 3.0.0 release notes but it seems that it didn't fix this scenario (I'm using 3.0.0 btw).

**Comment by roryprimrose** [comment]
Hi @webseb, can you please pull in the PR package to see if your issue has been resolved?

https://www.myget.org/feed/divergic/package/nuget/Divergic.Logging.Xunit/3.0.1-pullrequest0020-0004
