### ISSUE TITLE
Logging scope does not work across async control flows

### ISSUE THREAD

**Issue by roryprimrose** [roryprimrose/Divergic.Logging.Xunit#31]
Disposing a scope throws an exception popping off the stack because AsyncLocal<T> is not used to store scope state.

**Comment by ulrichb** [comment]
Same here.

My exception stack:
```plain
System.IndexOutOfRangeException
Index was outside the bounds of the array.
   at System.Collections.Generic.Stack`1.PushWithResize(T item)
   at System.Collections.Generic.Stack`1.Push(T item)
   at Divergic.Logging.Xunit.TestOutputLogger.BeginScope[TState](TState state)
   at Microsoft.Extensions.Logging.ScopeLogger.CreateScope[TState](TState state)
   at Microsoft.Extensions.Logging.Logger.BeginScope[TState](TState state)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass2_0`2.<DefineScope>b__0(ILogger logger, T1 arg1, T2 arg2)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.Log.BeginRequestPipelineScope(ILogger logger, HttpRequestMessage request)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
```

**Comment by ulrichb** [comment]
Wouldn't it be enough to use a ConcurrentStack in https://github.com/roryprimrose/Divergic.Logging.Xunit/blob/4ed9e665e28dceff1228cab4654f626d54d78226/Divergic.Logging.Xunit/TestOutputLogger.cs ?

**Comment by roryprimrose** [comment]
Unfortunately I haven't been able to reproduce this in a unit test. Do you have a code sample that reliably hits this issue?

**Comment by ulrichb** [comment]
@roryprimrose 

```C#
    public class Repro
    {
        private readonly ITestOutputHelper _output;

        public Repro(ITestOutputHelper output)
        {
            _output = output;
        }

        [Fact]
        public void UsingThreads()
        {
            var logger = _output.BuildLogger();

            var threads = Enumerable.Range(0, 10).Select(_ => new Thread((() =>
            {
                for (int i = 0; i < 100; i++)
                {
                    using (logger.BeginScope("My scope data"))
                    {
                    }
                }
            }))).ToList();

            threads.ForEach(x => x.Start());
            threads.ForEach(x => x.Join());
        }

        [Fact]
        public async Task UsingParallelTasks()
        {
            var logger = _output.BuildLogger();


            await Task.WhenAll(Enumerable.Range(0, 10).Select(_ => StartOnDefaultScheduler(() =>
            {
                for (int i = 0; i < 100; i++)
                {
                    using (logger.BeginScope("My scope data"))
                    {
                    }
                }

                return Task.CompletedTask;
            })).ToList());

            Task StartOnDefaultScheduler(Func<Task> asyncFunc)
            {
                return Task.Factory.StartNew(asyncFunc, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap();
            }
        }
    }
```

**Comment by roryprimrose** [comment]
@ulrichb Thanks, that is a great help. Can you verify whether this build fixes this issue for you - https://www.myget.org/feed/neovolve/package/nuget/Divergic.Logging.Xunit/3.5.1-bugfix-31-asyncs0001

Fix is at https://github.com/roryprimrose/Divergic.Logging.Xunit/commit/67b74e7b966394b113e51a0b653ae7d4605221cf

**Comment by ulrichb** [comment]
@roryprimrose Just tested it against with use case and no more exceptions 👍

**Comment by ulrichb** [comment]
@roryprimrose Many thanks! ❤️
